// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzcNh3eoJAkKG_QCUdAUTmxcEVqY9598',
    appId: '1:860557948844:web:2ed56073712627178a6c09',
    messagingSenderId: '860557948844',
    projectId: 'test-001-76b68',
    authDomain: 'test-001-76b68.firebaseapp.com',
    storageBucket: 'test-001-76b68.firebasestorage.app',
    measurementId: 'G-WJ0TB8V6XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSTOdaTDGGtKA8P15f1sIfj_9R4Edj5GI',
    appId: '1:860557948844:android:c2138d1d0cf2a67d8a6c09',
    messagingSenderId: '860557948844',
    projectId: 'test-001-76b68',
    storageBucket: 'test-001-76b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjq-lTer5QVdw_UdB53i8kmbrXO2hGI8s',
    appId: '1:860557948844:ios:ee8566aabb1892eb8a6c09',
    messagingSenderId: '860557948844',
    projectId: 'test-001-76b68',
    storageBucket: 'test-001-76b68.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjq-lTer5QVdw_UdB53i8kmbrXO2hGI8s',
    appId: '1:860557948844:ios:ee8566aabb1892eb8a6c09',
    messagingSenderId: '860557948844',
    projectId: 'test-001-76b68',
    storageBucket: 'test-001-76b68.firebasestorage.app',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBzcNh3eoJAkKG_QCUdAUTmxcEVqY9598',
    appId: '1:860557948844:web:7ecd9da451a0f8908a6c09',
    messagingSenderId: '860557948844',
    projectId: 'test-001-76b68',
    authDomain: 'test-001-76b68.firebaseapp.com',
    storageBucket: 'test-001-76b68.firebasestorage.app',
    measurementId: 'G-MJQLT8K4RM',
  );
}
